Loaded module: python3/3.6.2
Traceback (most recent call last):
  File "231107_read_data.py", line 14, in <module>
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1119, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1162, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/core/dtypes/common.py", line 563, in is_categorical_dtype
    return CategoricalDtype.is_dtype(arr_or_dtype)
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/core/dtypes/base.py", line 282, in is_dtype
    if isinstance(dtype, (ABCSeries, ABCIndexClass, ABCDataFrame, np.dtype)):
  File "/zhome/5a/4/181325/.local/lib/python3.6/site-packages/pandas/core/dtypes/generic.py", line 12, in _check
    return getattr(inst, attr, "_typ") in comp
KeyboardInterrupt
